services:
  fm_swift.object_store.registry:
    class: FM\SwiftBundle\ObjectStore\ObjectStoreRegistry

  fm_swift.object_store:
    abstract: true
    class: FM\SwiftBundle\ObjectStore\ObjectStore
    arguments:
      - null # store driver
      - null # metadata driver

  fm_swift.object_store.driver.filesystem:
    abstract: true
    class: FM\SwiftBundle\ObjectStore\Driver\FilesystemDriver
    factory_service: fm_swift.object_store.driver_factory.filesystem
    factory_method: getDriver
    arguments:
      - null # service

  fm_swift.object_store.driver_factory.filesystem:
    class: FM\SwiftBundle\ObjectStore\Driver\FilesystemDriverFactory
    arguments:
      - @filesystem
      - %fm_swift.root_dir%

  fm_swift.metadata.driver.file:
    abstract: true
    class: FM\SwiftBundle\Metadata\Driver\FileDriver
    factory_service: fm_swift.metadata.driver_factory.file
    factory_method: getDriver
    arguments:
      - null # service

  fm_swift.metadata.driver_factory.file:
    class: FM\SwiftBundle\Metadata\Driver\FileDriverFactory
    arguments:
      - %fm_swift.root_dir%

  fm_swift.metadata.driver.xattr:
    abstract: true
    class: FM\SwiftBundle\Metadata\Driver\XattrDriver
    factory_service: fm_swift.metadata.driver_factory.xattr
    factory_method: getDriver
    arguments:
      - null # service

  fm_swift.metadata.driver_factory.xattr:
    class: FM\SwiftBundle\Metadata\Driver\XattrDriverFactory
    arguments:
      - @fm_swift.object_store.driver_factory.filesystem

  fm_swift.listener.service:
    class: FM\SwiftBundle\EventListener\ServiceListener
    arguments: [@fm_keystone.service_manager, @fm_swift.object_store.registry]
    scope: request
    tags:
      - { name: kernel.event_listener, event: kernel.controller }
